### ISSUE TITLE
Output IAM email address for GCS bucket access

### ISSUE THREAD

**Issue by bradfordcp** [k8ssandra/k8ssandra-terraform#17]
With this information, we can then request a service account key with the `gcloud` CLI tool.

https://cloud.google.com/sdk/gcloud/reference/iam/service-accounts/keys/create

From there we can then configure Medusa to use the bucket and key.

┆Issue is synchronized with this [Jiraserver Task](https://k8ssandra.atlassian.net/browse/K8SSAND-173) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-173
┆Priority: Medium

**Comment by chrislovecnm** [comment]
We should just optionally create the bucket
