### ISSUE TITLE
Using `source` instead of `python3` fails when invoking python scripts

### ISSUE THREAD

**Issue by adejanovski** [k8ssandra/k8ssandra-terraform#28]
Invoking a python script using `source`  instead of `python3` can fail on Mac laptops (and possibly other OS as well) with the following error: `from: can't read /var/mail/google.cloud`

https://github.com/k8ssandra/k8ssandra-terraform/blob/4385cbacf2b4943119f5c13919ea38c9adff1422/gcp/scripts/init.sh#L34

┆Issue is synchronized with this [Jiraserver Task](https://k8ssandra.atlassian.net/browse/K8SSAND-479) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-479
┆Priority: Medium

**Comment by chaitu6022** [comment]
Update It slipped from my sight, Update init.sh script

**Comment by chaitu6022** [comment]
Update It slipped from my sight, Update init script
