### ISSUE TITLE
[GCP] Destroy command fails

### ISSUE THREAD

**Issue by adejanovski** [k8ssandra/k8ssandra-terraform#29]
Running `destroy` fails with the following error:

```
% make destroy "provider=gcp"
bash /Users/adejanovski/projets/cassandra/adejanovski/k8ssandra-terraform/gcp/scripts/destroy.sh
Following variables are configured
TF_VAR_environment: dev
TF_VAR_name: k8ssandra
TF_VAR_region: us-central-1
TF_VAR_project_id: us-central-1
/Users/adejanovski/projets/cassandra/adejanovski/k8ssandra-terraform/gcp/scripts/destroy.sh: line 44: end: command not found
make: *** [destroy] Error 127
```

It looks like the following line is responsible due to a call to an `end` command that doesn't exist:
https://github.com/k8ssandra/k8ssandra-terraform/blob/4385cbacf2b4943119f5c13919ea38c9adff1422/gcp/scripts/destroy.sh#L44

┆Issue is synchronized with this [Jiraserver Task](https://k8ssandra.atlassian.net/browse/K8SSAND-480) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-480
┆Priority: Medium

**Comment by chaitu6022** [comment]
@adejanovski unexpected comment on the destroy script, updated the code.
