### ISSUE TITLE
AWS console access to list and read resources.

### ISSUE THREAD

**Issue by chaitu6022** [k8ssandra/k8ssandra-terraform#38]
Required access to test ingress and other deployments `poweruser-eks` should have access to list and read EKS cluster resources.

┆Issue is synchronized with this [Jiraserver Bug](https://k8ssandra.atlassian.net/browse/K8SSAND-570) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-570
┆Priority: Medium

**Comment by chaitu6022** [comment]
https://docs.aws.amazon.com/eks/latest/userguide/security_iam_id-based-policy-examples.html#policy_example3 
please refer this document, look for "View nodes and workloads for all clusters in the AWS Management Console".

**Comment by chrislovecnm** [comment]
@bradfordcp I understand that we are trying to configure some complex security policies, but this is slowing us down a TON. I recommend that we talk about this next week on our call and pause work on AWS till @chaitu6022 has console access and maybe admin access in a project.

**Comment by chaitu6022** [comment]
I got the access, This issue is resolved.
