### ISSUE TITLE
terraform init question

### ISSUE THREAD

**Issue by johnsmartco** [k8ssandra/k8ssandra-terraform#47]
Hi Krishna chaitu6022.  I recently started over with a new GKE cluster (jsmart-k8ssandra-130) in my gcp-techpubs project. While following our own instructions in https://docs.k8ssandra.io/install/gke/, all was well, until I tried the `terraform init` step:

...
john.smart@jsmart-rmbp15 env % terraform init
**zsh: command not found: terraform**
john.smart@jsmart-rmbp15 env % pwd
/Users/john.smart/github/k8ssandra-terraform/gcp/env

Note that before that, I did:

...
john.smart@jsmart-rmbp15 gcp % gcloud config set compute/region us-central1
Updated property [compute/region].

john.smart@jsmart-rmbp15 gcp % gcloud config set compute/zone us-central1-c
Updated property [compute/zone].

john.smart@jsmart-rmbp15 gcp % gcloud config set project "gcp-techpubs"
Updated property [core/project].

john.smart@jsmart-rmbp15 gcp % export TF_VAR_environment=prod
john.smart@jsmart-rmbp15 gcp % export TF_VAR_name=k8ssandra
john.smart@jsmart-rmbp15 gcp % export TF_VAR_project_id=gcp-techpubs
john.smart@jsmart-rmbp15 gcp % export TF_VAR_region=us-central1

Any idea why terraform init wouldn't work from my client? Things to check?

┆Issue is synchronized with this [Jiraserver Bug](https://k8ssandra.atlassian.net/browse/K8SSAND-609) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-609
┆Priority: Medium

**Comment by johnsmartco** [comment]
cc: @bradfordcp

**Comment by chrislovecnm** [comment]
Do a

`which terraform`

Command for me please

**Comment by johnsmartco** [comment]
@chrislovecnm, thanks. Yeah I tried that before. Not found.  

john.smart@jsmart-rmbp15 env % **which terraform**
terraform not found

Is there an assumption in https://docs.k8ssandra.io/install/gke/ that we didn't cover?

I cloned the repo, of course.

**Comment by chrislovecnm** [comment]
You need to install the binary

**Comment by johnsmartco** [comment]
Had a good Slack chat with Krishna. We need to add a Prerequisites section with info from:

* https://github.com/k8ssandra/k8ssandra-terraform/tree/main/gcp#tools 
* And https://learn.hashicorp.com/tutorials/terraform/install-cli 

... in our 'Install K8ssandra on GKE' topic before users get to this section: 

https://docs.k8ssandra.io/install/gke/#provision-infrastructure

I'll take care of it after testing the end-to-end steps on my GKE environment. My apologies for not testing sooner.
