### ISSUE TITLE
Create TF for AWS

### ISSUE THREAD

**Issue by chrislovecnm** [k8ssandra/k8ssandra-terraform#6]
chaitu6022 can you flush this out and add a tentative completion date?

┆Issue is synchronized with this [Jiraserver Task](https://k8ssandra.atlassian.net/browse/K8SSAND-178) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-178
┆Priority: Medium

**Comment by chaitu6022** [comment]
Merged the AWS EKS Terraform code into main branch.
