### ISSUE TITLE
Create TF for Azure

### ISSUE THREAD

**Issue by chrislovecnm** [k8ssandra/k8ssandra-terraform#7]
chaitu6022 when you are done with AWS flush this out and add a due date

┆Issue is synchronized with this [Jiraserver Task](https://k8ssandra.atlassian.net/browse/K8SSAND-177) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-177
┆Priority: Medium

**Comment by chaitu6022** [comment]
Merged the terraform code into main branch.
